
POST http://localhost:3001/api/patients
Content-Type: application/json

{}

###

POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "Thomas",
  "dateOfBirth": "2000-12-01",
  "ssn": "0123-3456",
  "gender": "male",
  "occupation": "exemple"
}
