
GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QzIiwiaWQiOiI2NWFjY2UyNzBkMGQ4NDA2ZDg2MjdmOTciLCJpYXQiOjE3MDU4MzE3NzUsImV4cCI6MTcwNTkxODE3NX0.PacJNrLWfhd8V3fO7LYtHEGjF-iyy7sXYwqJb55kSis

{
	"title": "Perou",
	"author": "Clément",
	"url": "www.Clement-Perou.com",
	"likes": 33,
	"userId": "65acce270d0d8406d8627f97"
}

###

DELETE http://localhost:3003/api/blogs/65acee1fcb0be421849dd8e4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QzIiwiaWQiOiI2NWFjY2UyNzBkMGQ4NDA2ZDg2MjdmOTciLCJpYXQiOjE3MDU4MjM4MjksImV4cCI6MTcwNTkxMDIyOX0.Ly7NdnR5X2S8IDh6NUFc7IXE7B68FwZ9BqYyd0fOmaY


### // Users

GET http://localhost:3003/api/users

###

POST http://localhost:3003/api/users
Content-Type: application/json

{
	"username": "test3",
	"password": "1234",
	"name": "three"
}

### // Login

POST http://localhost:3003/api/login
Content-Type: application/json

{
	"username": "test3",
	"password": "1234"
}